### ISSUE TITLE
`F.broadcast(df)` doesn't mutate df

### ISSUE THREAD

**Issue by tdsmith** [mozilla/dscontrib#16]
https://github.com/mozilla/dscontrib/blob/e50ebbc8ff3805ba5d5e320c9a8e73bba44fa1f9/src/dscontrib/flawrence/experiment.py#L137

The broadcast method doesn't mutate the existing DataFrame or actually broadcast anything; it returns a new DataFrame with the broadcast flag set; this should be `enrollments = F.broadcast(enrollments)`.

Or dropped, if it works without it :) I've run into weird heisenbugs from broadcasts failing.

cite: https://github.com/apache/spark/blob/86cc907448f0102ad0c185e87fcc897d0a32707f/sql/core/src/main/scala/org/apache/spark/sql/functions.scala#L1046

**Comment by felixlawrence** [comment]
Ha! TIL.

The dataframe should be small enough to broadcast (the number of rows is the number of enrollments, and its columns are `client_id`, `branch` and `enrollment_date`), and it would likely be A Bad Thing if it were not broadcast.

Is there an accepted method of benchmarking pyspark query execution, or some other method of determining whether an 'optimization' is merely superstition?

**Comment by tdsmith** [comment]
To do benchmarking in a meaningful way you'd probably have to spin up a dedicated cluster of fixed size and restart the cluster between each test in order to avoid cache hits. I haven't seen anyone try here. You can get a query plan by calling `.explain()` on a DataFrame and then try to reason about it.

Some rambling: If it's small enough it'll get autobroadcast depending on the Spark cluster's settings. OTOH even though a lot of documentation seems to imply that shuffle joins are Just The Worst but they're so much faster than data access that I don't think I've ever experienced them as a pain point; I intentionally disable broadcast joins in my WebRender jobs because I was getting time-outs on broadcast that depended on the cluster scaling state and perf remained fine afterwards.

**Comment by felixlawrence** [comment]
OK, let's default to no broadcast hint - people can always do it manually. If in the future we find it does make a positive difference then we can start doing it by default without breaking the scripts of anyone who was doing it manually. I'll change this in my next commit or two.

**Comment by felixlawrence** [comment]
Fixed in 75ed68097fe1c1ac28595c2bcd7a3acf03c230b7.
