### ISSUE TITLE
Publish on pypi

### ISSUE THREAD

**Issue by felixlawrence** [mozilla/dscontrib#6]
There's a fatal flaw in the dscontrib+databricks workflow that could be alleviated if dscontrib were in pypi. Right now if I commit and push some changes, then in order to use those changes the databricks cluster needs to be restarted, which impacts everyone. I could get around this by installing dscontrib in an individual notebook using `dbutils.library.installPyPI` but this method doesn't support installing from `git+https`. So we should set up CI to publish on pypi after each commit to master.

**Comment by robhudson** [comment]
I can create a CircleCI workflow that will auto publish to pypi whenever a master commit is added. The version can be a date stamp with the format `YYYYmmDDHHMMSS`
